// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	model "github.com/abaron10/Posts-API-Golang/models"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// PostRepository is an autogenerated mock type for the PostRepository type
type PostRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *PostRepository) FindAll() ([]model.Post, error) {
	ret := _m.Called()

	var r0 []model.Post
	if rf, ok := ret.Get(0).(func() []model.Post); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: post
func (_m *PostRepository) Save(post *model.Post) (*model.Post, error) {
	ret := _m.Called(post)

	var r0 *model.Post
	if rf, ok := ret.Get(0).(func(*model.Post) *model.Post); ok {
		r0 = rf(post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Post) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostRepository creates a new instance of PostRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostRepository(t testing.TB) *PostRepository {
	mock := &PostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
